==23531== Memcheck, a memory error detector
==23531== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==23531== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==23531== Command: ./use_after_free_DeepState_TestHarness --fuzz
==23531== 
INFO: Starting fuzzing
WARNING: No seed provided; using 1592171406
WARNING: No test specified, defaulting to first test defined (use_after_free_random_datatypes_rcpp_use_after_free_test)
size_free values: -455305053
==23534== Argument 'size' of function malloc has a fishy (possibly negative) value: -1821220212
==23534==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==23534==    by 0x41822C: rcpp_use_after_free(int) (use_after_free.cpp:10)
==23534==    by 0x407F3D: DeepState_Test_use_after_free_random_datatypes_rcpp_use_after_free_test() (use_after_free_DeepState_TestHarness.cpp:16)
==23534==    by 0x407E18: DeepState_Run_use_after_free_random_datatypes_rcpp_use_after_free_test() (use_after_free_DeepState_TestHarness.cpp:7)
==23534==    by 0x405CB3: DeepState_RunTest.isra.6 (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==23534==    by 0x40DF0A: DeepState_FuzzOneTestCase (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==23534==    by 0x40E01F: DeepState_Fuzz (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==23534==    by 0x40628D: main (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==23534== 
==23534== Invalid read of size 4
==23534==    at 0x418238: rcpp_use_after_free(int) (use_after_free.cpp:12)
==23534==    by 0x407F3D: DeepState_Test_use_after_free_random_datatypes_rcpp_use_after_free_test() (use_after_free_DeepState_TestHarness.cpp:16)
==23534==    by 0x407E18: DeepState_Run_use_after_free_random_datatypes_rcpp_use_after_free_test() (use_after_free_DeepState_TestHarness.cpp:7)
==23534==    by 0x405CB3: DeepState_RunTest.isra.6 (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==23534==    by 0x40DF0A: DeepState_FuzzOneTestCase (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==23534==    by 0x40E01F: DeepState_Fuzz (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==23534==    by 0x40628D: main (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==23534==  Address 0x28 is not stack'd, malloc'd or (recently) free'd
==23534== 
==23534== 
==23534== Process terminating with default action of signal 11 (SIGSEGV)
==23534==  Access not within mapped region at address 0x28
==23534==    at 0x418238: rcpp_use_after_free(int) (use_after_free.cpp:12)
==23534==    by 0x407F3D: DeepState_Test_use_after_free_random_datatypes_rcpp_use_after_free_test() (use_after_free_DeepState_TestHarness.cpp:16)
==23534==    by 0x407E18: DeepState_Run_use_after_free_random_datatypes_rcpp_use_after_free_test() (use_after_free_DeepState_TestHarness.cpp:7)
==23534==    by 0x405CB3: DeepState_RunTest.isra.6 (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==23534==    by 0x40DF0A: DeepState_FuzzOneTestCase (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==23534==    by 0x40E01F: DeepState_Fuzz (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==23534==    by 0x40628D: main (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==23534==  If you believe this happened as a result of a stack
==23534==  overflow in your program's main thread (unlikely but
==23534==  possible), you can try to increase the size of the
==23534==  main thread stack using the --main-stacksize= flag.
==23534==  The main thread stack size used in this run was 8388608.
==23534== 
==23534== HEAP SUMMARY:
==23534==     in use at exit: 50,680,311 bytes in 9,739 blocks
==23534==   total heap usage: 27,607 allocs, 17,868 frees, 86,461,459 bytes allocated
==23534== 
==23534== LEAK SUMMARY:
==23534==    definitely lost: 0 bytes in 0 blocks
==23534==    indirectly lost: 0 bytes in 0 blocks
==23534==      possibly lost: 0 bytes in 0 blocks
==23534==    still reachable: 50,680,311 bytes in 9,739 blocks
==23534==         suppressed: 0 bytes in 0 blocks
==23534== Reachable blocks (those to which a pointer was found) are not shown.
==23534== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==23534== 
==23534== For counts of detected and suppressed errors, rerun with: -v
==23534== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
ERROR: Crashed: use_after_free_random_datatypes_rcpp_use_after_free_test
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
size_free values: -1786704416
==24096== Argument 'size' of function malloc has a fishy (possibly negative) value: -7146817664
==24096==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24096==    by 0x41822C: rcpp_use_after_free(int) (use_after_free.cpp:10)
==24096==    by 0x407F3D: DeepState_Test_use_after_free_random_datatypes_rcpp_use_after_free_test() (use_after_free_DeepState_TestHarness.cpp:16)
==24096==    by 0x407E18: DeepState_Run_use_after_free_random_datatypes_rcpp_use_after_free_test() (use_after_free_DeepState_TestHarness.cpp:7)
==24096==    by 0x405CB3: DeepState_RunTest.isra.6 (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==24096==    by 0x40DF0A: DeepState_FuzzOneTestCase (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==24096==    by 0x40E01F: DeepState_Fuzz (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==24096==    by 0x40628D: main (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==24096== 
==24096== Invalid read of size 4
==24096==    at 0x418238: rcpp_use_after_free(int) (use_after_free.cpp:12)
==24096==    by 0x407F3D: DeepState_Test_use_after_free_random_datatypes_rcpp_use_after_free_test() (use_after_free_DeepState_TestHarness.cpp:16)
==24096==    by 0x407E18: DeepState_Run_use_after_free_random_datatypes_rcpp_use_after_free_test() (use_after_free_DeepState_TestHarness.cpp:7)
==24096==    by 0x405CB3: DeepState_RunTest.isra.6 (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==24096==    by 0x40DF0A: DeepState_FuzzOneTestCase (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==24096==    by 0x40E01F: DeepState_Fuzz (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==24096==    by 0x40628D: main (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==24096==  Address 0x28 is not stack'd, malloc'd or (recently) free'd
==24096== 
==24096== 
==24096== Process terminating with default action of signal 11 (SIGSEGV)
==24096==  Access not within mapped region at address 0x28
==24096==    at 0x418238: rcpp_use_after_free(int) (use_after_free.cpp:12)
==24096==    by 0x407F3D: DeepState_Test_use_after_free_random_datatypes_rcpp_use_after_free_test() (use_after_free_DeepState_TestHarness.cpp:16)
==24096==    by 0x407E18: DeepState_Run_use_after_free_random_datatypes_rcpp_use_after_free_test() (use_after_free_DeepState_TestHarness.cpp:7)
==24096==    by 0x405CB3: DeepState_RunTest.isra.6 (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==24096==    by 0x40DF0A: DeepState_FuzzOneTestCase (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==24096==    by 0x40E01F: DeepState_Fuzz (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==24096==    by 0x40628D: main (in /home/akhila/R/RcppDeepState.Rcheck/tests/testthat/use_after_free_DeepState_TestHarness)
==24096==  If you believe this happened as a result of a stack
==24096==  overflow in your program's main thread (unlikely but
==24096==  possible), you can try to increase the size of the
==24096==  main thread stack using the --main-stacksize= flag.
==24096==  The main thread stack size used in this run was 8388608.
==24096== 
==24096== HEAP SUMMARY:
==24096==     in use at exit: 50,680,311 bytes in 9,739 blocks
==24096==   total heap usage: 27,606 allocs, 17,867 frees, 86,453,267 bytes allocated
==24096== 
==24096== LEAK SUMMARY:
==24096==    definitely lost: 0 bytes in 0 blocks
==24096==    indirectly lost: 0 bytes in 0 blocks
==24096==      possibly lost: 0 bytes in 0 blocks
==24096==    still reachable: 50,680,311 bytes in 9,739 blocks
==24096==         suppressed: 0 bytes in 0 blocks
==24096== Reachable blocks (those to which a pointer was found) are not shown.
==24096== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==24096== 
==24096== For counts of detected and suppressed errors, rerun with: -v
==24096== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
ERROR: Crashed: use_after_free_random_datatypes_rcpp_use_after_free_test
INFO: Done fuzzing! Ran 2 tests (0 tests/second) with 2 failed/0 passed/0 abandoned tests
==23531== 
==23531== HEAP SUMMARY:
==23531==     in use at exit: 8 bytes in 1 blocks
==23531==   total heap usage: 4 allocs, 3 frees, 106,568 bytes allocated
==23531== 
==23531== LEAK SUMMARY:
==23531==    definitely lost: 0 bytes in 0 blocks
==23531==    indirectly lost: 0 bytes in 0 blocks
==23531==      possibly lost: 0 bytes in 0 blocks
==23531==    still reachable: 8 bytes in 1 blocks
==23531==         suppressed: 0 bytes in 0 blocks
==23531== Reachable blocks (those to which a pointer was found) are not shown.
==23531== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==23531== 
==23531== For counts of detected and suppressed errors, rerun with: -v
==23531== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
